# Generated by Django 6.0.4 on 2026-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("municipality", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("dry_capacity", models.IntegerField(blank=True, null=True)),
                ("refrigerated_capacity", models.IntegerField(blank=True, null=True)),
                ("frozen_capacity", models.IntegerField(blank=True, null=True)),
                ("available_space", models.IntegerField(blank=True, null=True)),
                ("access_hours", models.CharField(blank=True, max_length=255)),
                ("restrictions", models.TextField(blank=True)),
                ("has_forklift", models.BooleanField(default=False)),
                ("has_pallet_jack", models.BooleanField(default=False)),
                ("has_loading_dock", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
