# Generated by Django 6.0.4 on 2026-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ['name'], 'verbose_name': 'Storage Location', 'verbose_name_plural': 'Storage Locations'},
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='accepted_food_types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('needs_update', 'Needs Update'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='approximate_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='capacity_status',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('full', 'Full'), ('unavailable', 'Temporarily Unavailable')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='contact_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='has_floor_jack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='has_hand_truck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='has_liftgate_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='has_ramp_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='max_load_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='max_pallet_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='owner_operator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='permission_level',
            field=models.CharField(choices=[('admin_only', 'Admin Only'), ('approved_members', 'Approved Members'), ('restricted_group', 'Restricted Group'), ('region_only', 'Region Only'), ('direct_partner', 'Direct Partner Only')], default='admin_only', max_length=50),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='province',
            field=models.CharField(default='British Columbia', max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='storage_type',
            field=models.CharField(choices=[('dry', 'Dry Storage'), ('refrigerated', 'Cold/Refrigerated Storage'), ('frozen', 'Frozen Storage'), ('warehouse', 'Palletized Warehouse Storage'), ('small_room', 'Small-Room Storage'), ('pantry', 'Community Pantry Storage'), ('kitchen', 'Commercial Kitchen Storage'), ('emergency', 'Temporary/Emergency Storage'), ('other', 'Other')], default='dry', max_length=50),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='available_space',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='dry_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='frozen_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='refrigerated_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
