services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: fcacp
      POSTGRES_PASSWORD: super-secure-password
    ports:
      - protocol: tcp
        target: 5432
        published: 5432
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql

  mail:
    image: axllent/mailpit:v1.27
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - protocol: tcp
        target: 8025
        published: 8025
      - protocol: tcp
        target: 1025
        published: 1025

  celery:
    build: .
    command: celery -A fcacp worker -l info
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DATABASE_URL: postgresql://fcacp:super-secure-password@database:5432/fcacp
      CELERY_BROKER_URL: ${FCACP_DOCKER_CELERY_BROKER_URL:-redis://host.docker.internal:6379/0}
      CLAMAV_HOST: ${FCACP_DOCKER_CLAMAV_HOST:-host.docker.internal}
      CLAMAV_PORT: ${FCACP_DOCKER_CLAMAV_PORT:-3310}
    volumes:
      - ./private_media:/app/private_media

volumes:
  database:
