services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: fcacp
      POSTGRES_PASSWORD: super-secure-password
    ports:
      - protocol: tcp
        target: 5432
        published: 5432
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql

  mail:
    image: axllent/mailpit:v1.27
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - protocol: tcp
        target: 8025
        published: 8025
      - protocol: tcp
        target: 1025
        published: 1025

  redis:
    image: redis:alpine
    ports:
      - protocol: tcp
        target: 6379
        published: 6379

  clamav:
    image: clamav/clamav:stable
    ports:
      - protocol: tcp
        target: 3310
        published: 3310
    volumes:
      - clamav-db:/var/lib/clamav

  garage:
    build: services/garage
    environment:
      GARAGE_DEFAULT_BUCKET: thefoodcharity-dev
      GARAGE_DEFAULT_ACCESS_KEY: gk-dev-access-key
      GARAGE_DEFAULT_SECRET_KEY: dev-secret-access-key
    ports:
      - protocol: tcp
        target: 3900
        published: 3900
    volumes:
      - garage:/var/lib/garage

volumes:
  database:
  clamav-db:
  garage:
