[project]
name = "fcacp"
version = "0.1.0"
description = "The platform for the Food Charity Association of Canada"
authors = [
    { name = "Erryl Galang", email = "egalang6@my.bcit.ca" },
    { name = "Ramandeep Kaur", email = "rramandeepkaur11@my.bcit.ca" },
    { name = "Alex Krantz", email = "alex@krantz.dev" },
    { name = "Jiahong Xu", email = "jiahongxu1997@gmail.com" },
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.4",
    "django-tailwind>=4.4.2",
    "psycopg[binary,pool]>=3.3.3",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
]

[dependency-groups]
dev = [
    "cookiecutter>=2.7.1",
    "django-browser-reload>=1.21.0",
    "prek>=0.3.11",
    "ruff>=0.15.12",
]
prod = [
    "gunicorn>=25.3.0",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
select = ["C4", "DJ", "E", "F", "I", "LOG", "PTH", "RUF", "TD", "TRY"]
ignore = ["TRY003"]
