[project]
name = "fcacp"
version = "0.1.0"
description = "The platform for the Food Charity Association of Canada"
authors = [
    { name = "Erryl Galang", email = "egalang6@my.bcit.ca" },
    { name = "Ramandeep Kaur", email = "rramandeepkaur11@my.bcit.ca" },
    { name = "Alex Krantz", email = "alex@krantz.dev" },
    { name = "Jiahong Xu", email = "jiahongxu1997@gmail.com" },
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.4",
    "django-debug-toolbar>=6.3.0",
    "django-htmx>=1.27.0",
    "django-organizations>=2.6.0",
    "psycopg[binary,pool]>=3.3.3",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
]

[dependency-groups]
dev = [
    "prek>=0.3.11",
    "ruff>=0.15.12",
]
prod = [
    "gunicorn>=25.3.0",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
select = ["C4", "DJ", "E", "F", "I", "LOG", "PTH", "RUF", "TD", "TID", "TRY"]
ignore = ["RUF012", "TD003", "TRY003"]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"django.contrib.auth.models.User".msg = "Import User from accounts.models instead."
"django.contrib.auth.models.Group".msg = "Import Group from accounts.models instead."

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["E501"]
