# Generated by Django 6.0.4 on 2026-05-06 23:02

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "legal status",
                "verbose_name_plural": "legal statuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "organization type",
                "verbose_name_plural": "organization types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_via_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_via_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, help_text="Brief organization description"),
        ),
        migrations.AddField(
            model_name="organization",
            name="interest_areas",
            field=models.TextField(blank=True, help_text="Main interest areas and project interests"),
        ),
        migrations.AddField(
            model_name="organization",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_publicly_visible",
            field=models.BooleanField(
                default=False, help_text="Whether this organization may appear on public maps or directories"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="municipality",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="region",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="service_area",
            field=models.TextField(blank=True, help_text="Geographic or community area the organization serves"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, help_text="Public-facing contact email", max_length=254),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                help_text="Primary internal contact responsible for membership, onboarding, and operational communication",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, help_text="Public-facing contact phone", max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Pending"),
                    (2, "Approved"),
                    (3, "Approved with limited access"),
                    (4, "Needs more information"),
                    (5, "Declined"),
                    (6, "Archived"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, help_text="Public-facing website"),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.legalstatus",
                verbose_name="legal / organizational status",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_acknowledgements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organization application",
                "verbose_name_plural": "organization applications",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organizationtype",
                verbose_name="organization type",
            ),
        ),
    ]
