# Generated by Django 6.0.4 on 2026-05-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_seed_organization_types_and_legal_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationapplication",
            name="basics_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationapplication",
            name="contact_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationapplication",
            name="location_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationapplication",
            name="operations_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
