# Generated by Django 6.0.4 on 2026-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organizationapplication_form_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
