# Generated by Django 6.0.4 on 2026-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_organization_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="membership",
            name="permission_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
