# Generated by Django 6.0.4 on 2026-05-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_remove_membership_is_admin_and_more"),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"scope": 1},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="permissions.permissiongroup",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="The capabilities this organization has been granted.",
                limit_choices_to={"scope": 2},
                related_name="organizations",
                to="permissions.permissiongroup",
                verbose_name="capabilities",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="permission_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
