# Generated by Django 6.0.4 on 2026-05-15 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_membership_role_organization_capabilities_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="invitee_identifier",
            new_name="email",
        ),
    ]
