# Generated by Django 6.0.4 on 2026-05-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_membership_role_organization_capabilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
