# Generated by Django 6.0.4 on 2026-05-14 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_organization_address_line_1_and_more"),
        ("organizations", "0008_permissions_organizations"),
    ]

    operations = []
