# Generated by Django 6.0.4 on 2026-05-16 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_rename_invitee_identifier_invitation_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="invitee",
        ),
    ]
