# Generated by Django 6.0.4 on 2026-05-16 06:08

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "__first__"),
        ("organizations", "0009_remove_invitation_invitee"),
        ("permissions", "0003_permissions_organizations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={"verbose_name": "invitation", "verbose_name_plural": "invitations"},
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="guid",
        ),
        migrations.AddField(
            model_name="invitation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 5, 16, 1, 20, 44, 57852, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"scope": 1},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="permissions.permissiongroup",
                verbose_name="role",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accepted_at__isnull", True)),
                fields=("organization", "email"),
                name="unique_pending_invitation_per_org_email",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
