# Generated by Django 6.0.4 on 2026-05-16 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_organization_latitude_organization_longitude"),
        ("organizations", "0010_alter_invitation_options_remove_invitation_guid_and_more"),
    ]

    operations = []
