# Generated by Django 6.0.4 on 2026-05-07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborations", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationSpace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                (
                    "topic_category",
                    models.CharField(
                        choices=[
                            ("food_supply", "Food supply"),
                            ("storage", "Storage"),
                            ("distribution", "Distribution"),
                            ("volunteers", "Volunteers"),
                            ("emergency_response", "Emergency response"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                (
                    "visibility_level",
                    models.CharField(
                        choices=[
                            ("admin_only", "Admin only"),
                            ("invite_only", "Invite only"),
                            ("approved_members", "Approved members"),
                            ("region_only", "Region only"),
                        ],
                        default="invite_only",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_collaboration_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="space",
                        to="collaborations.collaborationspacerequest",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderated_collaboration_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_collaboration_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationLinkedObject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_id", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collaboration_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_objects",
                        to="collaborations.collaborationspace",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationSpaceOrganizationMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                            ("readonly", "Read only"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("full", "Full access"),
                            ("moderate", "Moderate"),
                            ("contribute", "Contribute"),
                            ("readonly", "Read only"),
                        ],
                        default="contribute",
                        max_length=50,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_post", models.BooleanField(default=True)),
                ("can_invite", models.BooleanField(default=False)),
                ("can_upload", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_space_memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to="collaborations.collaborationspace",
                    ),
                ),
            ],
            options={
                "ordering": ["space", "organization"],
                "unique_together": {("space", "organization")},
            },
        ),
        migrations.CreateModel(
            name="CollaborationSpaceUserMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                            ("readonly", "Read only"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("full", "Full access"),
                            ("moderate", "Moderate"),
                            ("contribute", "Contribute"),
                            ("readonly", "Read only"),
                        ],
                        default="contribute",
                        max_length=50,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_post", models.BooleanField(default=True)),
                ("can_invite", models.BooleanField(default=False)),
                ("can_upload", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="collaborations.collaborationspace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_space_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["space", "user"],
                "unique_together": {("space", "user")},
            },
        ),
    ]
