# Generated by Django 6.0.4 on 2026-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collaborations", "0003_collaboration_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborationspaceorganizationmembership",
            name="can_invite",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceorganizationmembership",
            name="can_moderate",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceorganizationmembership",
            name="can_post",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceorganizationmembership",
            name="can_upload",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceorganizationmembership",
            name="can_view",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceorganizationmembership",
            name="permission_level",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceusermembership",
            name="can_invite",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceusermembership",
            name="can_moderate",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceusermembership",
            name="can_post",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceusermembership",
            name="can_upload",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceusermembership",
            name="can_view",
        ),
        migrations.RemoveField(
            model_name="collaborationspaceusermembership",
            name="permission_level",
        ),
    ]
