# Generated by Django 6.0.4 on 2026-05-13 16:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import collaborations.models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborations", "0004_use_membership_roles_for_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to=collaborations.models.collaboration_file_upload_to)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="collaborations.collaborationspace",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_collaboration_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "original_filename"],
            },
        ),
    ]
