# Generated by Django 6.0.4 on 2026-05-14 17:15

from django.db import migrations, models

import collaborations.models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborations", "0005_collaborationfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborationfile",
            name="scan_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collaborationfile",
            name="scan_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collaborationfile",
            name="scan_result",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="collaborationfile",
            name="scan_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collaborationfile",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending scan"),
                    ("scanning", "Scanning"),
                    ("clean", "Clean"),
                    ("infected", "Infected"),
                    ("failed", "Scan failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="collaborationfile",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collaborationfile",
            name="file",
            field=models.FileField(max_length=255, upload_to=collaborations.models.collaboration_file_upload_to),
        ),
    ]
