# Generated by Django 6.0.4 on 2026-05-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0006_remove_membership_is_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationPermissionOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("effect", models.PositiveSmallIntegerField(choices=[(1, "Allow"), (2, "Deny")])),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="organizations.organization",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="permissions.permission"),
                ),
            ],
            options={
                "verbose_name": "organization permission override",
                "verbose_name_plural": "organization permission overrides",
                "unique_together": {("organization", "permission")},
            },
        ),
        migrations.CreateModel(
            name="MembershipPermissionOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("effect", models.PositiveSmallIntegerField(choices=[(1, "Allow"), (2, "Deny")])),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="organizations.membership",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="permissions.permission"),
                ),
            ],
            options={
                "verbose_name": "membership permission override",
                "verbose_name_plural": "membership permission overrides",
                "unique_together": {("membership", "permission")},
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("scope", models.PositiveSmallIntegerField(choices=[(1, "User role"), (2, "Organization capability")])),
                ("description", models.CharField(blank=True, max_length=500)),
                ("is_system", models.BooleanField(default=False)),
                ("permissions", models.ManyToManyField(blank=True, related_name="groups", to="permissions.permission")),
            ],
            options={
                "verbose_name": "permission group",
                "verbose_name_plural": "permission groups",
                "ordering": ("scope", "name"),
                "unique_together": {("name", "scope")},
            },
        ),
    ]
