# Generated by Django 6.0.4 on 2026-05-14 18:04

from django.db import migrations

from permissions.constants import Scope, SystemCapability, SystemRole

USER_ROLES = [
    (SystemRole.FOOD_CHARITY_ADMIN, "Platform administration and moderation."),
    (SystemRole.ORGANIZATION_MANAGER, "Manage an organization's profile, members, and submissions."),
    (SystemRole.ORGANIZATION_USER, "Standard member access within an organization."),
]

ORGANIZATION_CAPABILITIES = [
    (SystemCapability.DEFAULT, "Default capability granted to all approved organizations."),
    (SystemCapability.FOOD_DONOR, "Submit and manage food supply listings."),
    (SystemCapability.FOOD_RECEIVER, "Express interest in food listings and confirm receipt."),
    (SystemCapability.STORAGE_PROVIDER, "Submit and maintain storage location records."),
    (SystemCapability.COLLABORATION_PARTICIPANT, "Participate in invited working groups and collaboration spaces."),
    (SystemCapability.FORUM_PARTICIPANT, "Participate in member-only forum and discussion spaces."),
    (SystemCapability.READ_ONLY, "View-only access to permitted resources."),
]


def seed_permission_groups(apps, schema_editor):
    PermissionGroup = apps.get_model("permissions", "PermissionGroup")

    for name, description in USER_ROLES:
        PermissionGroup.objects.update_or_create(
            name=name,
            scope=Scope.USER.value,
            defaults={"description": description, "is_system": True},
        )

    for name, description in ORGANIZATION_CAPABILITIES:
        PermissionGroup.objects.update_or_create(
            name=name,
            scope=Scope.ORGANIZATION.value,
            defaults={"description": description, "is_system": True},
        )


def unseed_permission_groups(apps, schema_editor):
    PermissionGroup = apps.get_model("permissions", "PermissionGroup")
    all_names = [name for name, _ in USER_ROLES + ORGANIZATION_CAPABILITIES]
    PermissionGroup.objects.filter(name__in=all_names, is_system=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_permission_groups, reverse_code=unseed_permission_groups),
    ]
