# Generated by Django 6.0.4 on 2026-05-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Approved"),
                    (2, "Approved with limited access"),
                    (3, "Needs more information"),
                    (4, "Declined"),
                    (5, "Archived"),
                ],
                default=0,
            ),
        ),
    ]
