# Generated by Django 6.0.4 on 2026-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_remove_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user's email has been verified as active.",
                verbose_name="email verified",
            ),
        ),
    ]
