# Generated by Django 6.0.4 on 2026-05-05 19:23

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_remove_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
                "ordering": ["organization", "user"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("name", models.CharField(help_text="The name of the organization", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="The name in all lowercase, suitable for URL identification",
                        max_length=200,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Approved"),
                            (2, "Approved with limited access"),
                            (3, "Needs more information"),
                            (4, "Declined"),
                            (5, "Archived"),
                        ],
                        default=0,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ("website", models.URLField(blank=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="accounts_organization", through="accounts.Membership", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_users",
                to="accounts.organization",
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("guid", models.UUIDField(editable=False)),
                (
                    "invitee_identifier",
                    models.CharField(
                        help_text="The contact identifier for the invitee, email, phone number, social media handle, etc.",
                        max_length=1000,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_invitation_sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_invitation_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_invites",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationOwner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owner", to="accounts.organization"
                    ),
                ),
                (
                    "organization_user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="accounts.membership"),
                ),
            ],
            options={
                "verbose_name": "organization owner",
                "verbose_name_plural": "organization owners",
            },
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "organization")},
        ),
    ]
