# Generated by Django 6.0.4 on 2026-05-13 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_verificationcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
    ]
