# Generated by Django 6.0.4 on 2026-05-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_delete_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="verificationcode",
            name="unique_active_code_per_user_purpose",
        ),
        migrations.AddConstraint(
            model_name="verificationcode",
            constraint=models.UniqueConstraint(fields=("user",), name="unique_active_code_per_user"),
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="purpose",
        ),
    ]
