# Generated by Django 6.0.4 on 2026-05-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage", "0002_alter_storagelocation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("donor_name", models.CharField(max_length=255)),
                ("donor_contact", models.CharField(blank=True, max_length=255)),
                (
                    "food_category",
                    models.CharField(
                        choices=[
                            ("produce", "Fresh Produce"),
                            ("refrigerated", "Perishable Refrigerated"),
                            ("frozen", "Frozen"),
                            ("dry_goods", "Dry Goods"),
                            ("canned", "Canned/Shelf-Stable"),
                            ("prepared", "Prepared Food"),
                            ("bulk", "Bulk Ingredients"),
                            ("palletized", "Palletized Goods"),
                            ("mixed", "Small Mixed Donation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("food_type", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit", models.CharField(default="items", max_length=50)),
                ("estimated_weight", models.PositiveIntegerField(blank=True, null=True)),
                ("pickup_location", models.CharField(max_length=255)),
                ("pickup_window", models.CharField(blank=True, max_length=255)),
                ("pickup_deadline", models.DateTimeField()),
                ("best_before_date", models.DateField(blank=True, null=True)),
                (
                    "storage_requirement",
                    models.CharField(
                        choices=[
                            ("dry", "Dry Storage"),
                            ("refrigerated", "Refrigerated Storage"),
                            ("frozen", "Frozen Storage"),
                            ("none", "No Storage Needed"),
                        ],
                        default="dry",
                        max_length=50,
                    ),
                ),
                ("temperature_requirement", models.CharField(blank=True, max_length=100)),
                ("requires_van", models.BooleanField(default=False)),
                ("requires_cube_van", models.BooleanField(default=False)),
                ("requires_refrigerated_vehicle", models.BooleanField(default=False)),
                ("requires_pallet_jack", models.BooleanField(default=False)),
                ("requires_forklift", models.BooleanField(default=False)),
                ("loading_dock_available", models.BooleanField(default=False)),
                ("donor_can_help_load", models.BooleanField(default=False)),
                ("special_handling_notes", models.TextField(blank=True)),
                ("chain_of_custody_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("in_transit", "In Transit"),
                            ("stored", "Stored"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_tickets",
                        to="storage.storagelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation Ticket",
                "verbose_name_plural": "Donation Tickets",
                "ordering": ["-created_at"],
            },
        ),
    ]
