import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_rename_donationticket_donation"),
        ("storage", "0002_alter_storagelocation_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS donations_foodrequest (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        receiver_name varchar(255) NOT NULL,
                        organization varchar(255) NOT NULL,
                        email varchar(254) NOT NULL,
                        phone varchar(50) NOT NULL,
                        requested_quantity integer NOT NULL CHECK (requested_quantity >= 0),
                        requested_unit varchar(50) NOT NULL,
                        storage_required boolean NOT NULL DEFAULT false,
                        storage_notes text NOT NULL,
                        notes text NOT NULL,
                        status varchar(50) NOT NULL,
                        created_at timestamp with time zone NOT NULL,
                        updated_at timestamp with time zone NOT NULL,
                        donation_id bigint NOT NULL
                            REFERENCES donations_donationticket(id)
                            DEFERRABLE INITIALLY DEFERRED,
                        preferred_storage_id bigint NULL
                            REFERENCES storage_storagelocation(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="FoodRequest",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("receiver_name", models.CharField(max_length=255)),
                        ("organization", models.CharField(blank=True, max_length=255)),
                        ("email", models.EmailField(max_length=254)),
                        ("phone", models.CharField(blank=True, max_length=50)),
                        ("requested_quantity", models.PositiveIntegerField()),
                        (
                            "requested_unit",
                            models.CharField(
                                choices=[
                                    ("items", "Items"),
                                    ("boxes", "Boxes"),
                                    ("cases", "Cases"),
                                    ("bags", "Bags"),
                                    ("pallets", "Pallets"),
                                    ("kg", "Kilograms"),
                                    ("lb", "Pounds"),
                                    ("litres", "Litres"),
                                ],
                                default="items",
                                max_length=50,
                            ),
                        ),
                        ("storage_required", models.BooleanField(default=False)),
                        ("storage_notes", models.TextField(blank=True)),
                        ("notes", models.TextField(blank=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("submitted", "Submitted"),
                                    ("approved", "Approved"),
                                    ("declined", "Declined"),
                                    ("fulfilled", "Fulfilled"),
                                    ("cancelled", "Cancelled"),
                                ],
                                default="submitted",
                                max_length=50,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "donation",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="food_requests",
                                to="donations.donation",
                            ),
                        ),
                        (
                            "preferred_storage",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="food_requests",
                                to="storage.storagelocation",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Food Request",
                        "verbose_name_plural": "Food Requests",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
        ),
    ]
