# Generated by Django 6.0.4 on 2026-05-11 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0006_update_food_type_and_unit_choices"),
        ("storage", "0002_alter_storagelocation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="food_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="assigned_storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="storage.storagelocation",
            ),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="requested_unit",
            field=models.CharField(
                choices=[
                    ("items", "Items"),
                    ("small_bags", "Small bags"),
                    ("large_bags", "Large bags"),
                    ("boxes", "Boxes"),
                    ("cases", "Cases"),
                    ("bags", "Bags"),
                    ("crates", "Crates"),
                    ("flats", "Flats"),
                    ("gallons", "Gallons"),
                    ("gaylords", "Gaylords"),
                    ("pallets", "Pallets"),
                    ("trays", "Trays"),
                    ("kg", "Kilograms"),
                    ("lb", "Pounds"),
                    ("litres", "Litres"),
                    ("other", "Other"),
                ],
                default="items",
                max_length=50,
            ),
        ),
    ]
