# Generated by Django 6.0.4 on 2026-05-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0007_donation_submitted_by_foodrequest_requested_by_and_more"),
        ("organizations", "0004_organizationapplication_form_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="supplier_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="receiver_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="food_requests",
                to="organizations.organization",
            ),
        ),
    ]
