# Generated by Django 6.0.4 on 2026-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0008_donation_supplier_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="address_1",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="address_2",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="donor_contact",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="donor_name",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="province_or_state",
        ),
    ]
