# Generated by Django 6.0.4 on 2026-05-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0009_remove_donation_address_1_remove_donation_address_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="pickup_ready_time",
            field=models.CharField(
                choices=[
                    ("ready_now", "It is packaged and ready to go"),
                    ("8am", "From 8am"),
                    ("9am", "From 9am"),
                    ("10am", "From 10am"),
                    ("11am", "From 11am"),
                    ("12pm", "From 12pm"),
                    ("1pm", "From 1pm"),
                    ("2pm", "From 2pm"),
                    ("3pm", "From 3pm"),
                ],
                default="ready_now",
                max_length=30,
            ),
        ),
    ]
