# Generated by Django 6.0.4 on 2026-05-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0010_alter_donation_pickup_ready_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="estimated_weight",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="estimated_weight_unit",
        ),
        migrations.AlterField(
            model_name="donation",
            name="pickup_end_time",
            field=models.CharField(
                choices=[
                    ("before_noon", "Before noon"),
                    ("before_1pm", "Before 1pm"),
                    ("before_2pm", "Before 2pm"),
                    ("before_3pm", "Before 3pm"),
                    ("before_4pm", "Before 4pm"),
                    ("before_5pm", "Before 5pm"),
                ],
                default="before_5pm",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="pickup_ready_time",
            field=models.CharField(
                choices=[
                    ("ready_now", "It is packaged and ready to go"),
                    ("8am", "From 8am"),
                    ("9am", "From 9am"),
                    ("10am", "From 10am"),
                    ("11am", "From 11am"),
                    ("12pm", "From 12pm"),
                    ("1pm", "From 1pm"),
                    ("2pm", "From 2pm"),
                    ("3pm", "From 3pm"),
                    ("4pm", "From 4pm"),
                    ("5pm", "From 5pm"),
                ],
                default="ready_now",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("available", "Available"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="submitted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="unit",
            field=models.CharField(
                choices=[
                    ("bags", "Bags"),
                    ("boxes", "Boxes"),
                    ("cases", "Cases"),
                    ("pallets", "Pallets"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="donationfooditem",
            name="packaging",
            field=models.CharField(
                choices=[
                    ("bags", "Bags"),
                    ("boxes", "Boxes"),
                    ("cases", "Cases"),
                    ("pallets", "Pallets"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="requested_unit",
            field=models.CharField(
                choices=[
                    ("bags", "Bags"),
                    ("boxes", "Boxes"),
                    ("cases", "Cases"),
                    ("pallets", "Pallets"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
