# Generated by Django 6.0.4 on 2026-05-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0011_remove_donation_estimated_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodrequest",
            name="email",
        ),
        migrations.RemoveField(
            model_name="foodrequest",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="foodrequest",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="foodrequest",
            name="receiver_name",
        ),
        migrations.RemoveField(
            model_name="foodrequest",
            name="requested_quantity",
        ),
        migrations.RemoveField(
            model_name="foodrequest",
            name="requested_unit",
        ),
        migrations.CreateModel(
            name="FoodRequestAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                (
                    "donation_food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_allocations",
                        to="donations.donationfooditem",
                    ),
                ),
                (
                    "food_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="donations.foodrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Request Allocation",
                "verbose_name_plural": "Food Request Allocations",
                "ordering": ["id"],
            },
        ),
    ]
