# Generated by Django 6.0.4 on 2026-05-13 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0012_remove_foodrequest_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation",
            old_name="pickup_window",
            new_name="pickup_notes",
        ),
    ]
