# Generated by Django 6.0.4 on 2026-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0018_alter_donation_status_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="receiver_limit",
            field=models.CharField(
                choices=[("one", "1 receiver only"), ("two", "Maximum 2 receivers"), ("no_limit", "No limit")],
                default="one",
                max_length=20,
                verbose_name="maximum number of receivers",
            ),
        ),
    ]
