# Generated by Django 6.0.4 on 2026-05-11 18:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    atomic = True

    dependencies = [
        ("organizations", "0004_organizationapplication_form_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumSpaceRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                (
                    "topic_category",
                    models.CharField(
                        choices=[
                            ("general", "General discussion"),
                            ("regional", "Regional discussion"),
                            ("food_supply", "Food supply"),
                            ("storage", "Storage"),
                            ("transportation", "Transportation"),
                            ("funding", "Funding"),
                            ("advocacy", "Advocacy"),
                            ("education", "Education / training"),
                            ("emergency_response", "Emergency response"),
                            ("working_group", "Working group"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                ("suggested_participants", models.TextField(blank=True)),
                (
                    "visibility_preference",
                    models.CharField(
                        choices=[
                            ("invite_only", "Invite only"),
                            ("approved_members", "Approved members"),
                            ("region_only", "Region only"),
                        ],
                        default="invite_only",
                        max_length=50,
                    ),
                ),
                ("reason_for_request", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("needs_info", "Needs more information"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forum_space_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forum_space_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_forum_space_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
