# Generated by Django 6.0.4 on 2026-05-05 05:01

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = []

    operations: ClassVar = [
        migrations.CreateModel(
            name="FoodDonation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("donor_name", models.CharField(max_length=120)),
                ("organization", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("produce", "Fresh produce"),
                            ("bakery", "Bakery"),
                            ("packaged", "Packaged goods"),
                            ("prepared", "Prepared meals"),
                            ("frozen", "Frozen items"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.CharField(max_length=80)),
                ("best_before", models.DateField(blank=True, null=True)),
                ("pickup_address", models.TextField()),
                ("pickup_window", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("confirm_safe", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
