# Generated by Django 6.0.4 on 2026-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("public", "0002_delete_fooddonation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodHelpLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("food_bank", "Food Bank"),
                            ("food_hub", "Food Hub"),
                            ("meal_program", "Meal Program"),
                            ("community_pantry", "Community Pantry"),
                            ("shelter", "Shelter"),
                            ("senior_support", "Senior Food Support"),
                            ("youth_family", "Youth / Family Support"),
                            ("indigenous_program", "Indigenous-led Program"),
                            ("emergency_food", "Emergency Food Support"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("municipality", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("service_area", models.CharField(blank=True, max_length=160)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("days_open", models.CharField(blank=True, max_length=120)),
                ("hours_open", models.CharField(blank=True, max_length=120)),
                ("eligibility_requirements", models.TextField(blank=True)),
                ("accessibility_notes", models.TextField(blank=True)),
                ("languages_served", models.CharField(blank=True, max_length=160)),
                ("appointment_required", models.BooleanField(default=False)),
                ("walk_ins_accepted", models.BooleanField(default=True)),
                ("registration_required", models.BooleanField(default=False)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("last_verified", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("municipality", "name"),
            },
        ),
    ]
